function coeffs_a_opt = coeffs_a_opt(t,in2)
%COEFFS_A_OPT
%    COEFFS_A_OPT = COEFFS_A_OPT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Sep-2025 23:16:32

c2 = in2(:,2);
c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
c6 = in2(:,6);
t2 = t.^3;
coeffs_a_opt = c2+c3.*t+(c5.*t2)./6.0+c6.*t2.*2.0e+1+(c4.*t.^2)./2.0;
end
