function coeffs_j_opt = coeffs_j_opt(t,in2)
%COEFFS_J_OPT
%    COEFFS_J_OPT = COEFFS_J_OPT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Oct-2025 11:34:51

c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
c6 = in2(:,6);
t2 = t.^2;
coeffs_j_opt = c3+c4.*t+(c5.*t2)./2.0+c6.*t2.*6.0e+1;
end
