function coeffs_v_opt = coeffs_v_opt(t,in2)
%COEFFS_V_OPT
%    COEFFS_V_OPT = COEFFS_V_OPT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Oct-2025 11:34:51

c1 = in2(:,1);
c2 = in2(:,2);
c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
c6 = in2(:,6);
t2 = t.^4;
coeffs_v_opt = c1+c2.*t+(c5.*t2)./2.4e+1+c6.*t2.*5.0+(c3.*t.^2)./2.0+(c4.*t.^3)./6.0;
end
