function final_opt_time_stop_var = final_opt_time_stop(v0,a0,sf)
%FINAL_OPT_TIME_STOP
%    FINAL_OPT_TIME_STOP_VAR = FINAL_OPT_TIME_STOP(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    10-Oct-2025 12:31:13

t2 = v0.*2.0;
t3 = v0.^2;
t4 = a0.*sf.*5.0;
t5 = t3.*4.0;
t6 = t4+t5;
t7 = sqrt(t6);
final_opt_time_stop_var = [(sf.*1.0e+1)./(t2+t7);(sf.*1.0e+1)./(t2-t7)];
end
