function final_opt_time_pass_var = final_opt_time_pass(v0,a0,sf,vf)
%FINAL_OPT_TIME_PASS
%    FINAL_OPT_TIME_PASS_VAR = FINAL_OPT_TIME_PASS(V0,A0,SF,VF)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Oct-2025 11:08:04

t0 = roots([sf.^2.*1.2e+3,sf.*v0.*-9.6e+2-sf.*vf.*9.6e+2,a0.*sf.*-1.2e+2+v0.*vf.*3.36e+2+v0.^2.*1.92e+2+vf.^2.*1.92e+2,a0.*v0.*4.8e+1+a0.*vf.*3.2e+1,a0.^2.*3.0]);
t2 = t0(1);
t0 = roots([sf.^2.*1.2e+3,sf.*v0.*-9.6e+2-sf.*vf.*9.6e+2,a0.*sf.*-1.2e+2+v0.*vf.*3.36e+2+v0.^2.*1.92e+2+vf.^2.*1.92e+2,a0.*v0.*4.8e+1+a0.*vf.*3.2e+1,a0.^2.*3.0]);
t3 = t0(2);
t0 = roots([sf.^2.*1.2e+3,sf.*v0.*-9.6e+2-sf.*vf.*9.6e+2,a0.*sf.*-1.2e+2+v0.*vf.*3.36e+2+v0.^2.*1.92e+2+vf.^2.*1.92e+2,a0.*v0.*4.8e+1+a0.*vf.*3.2e+1,a0.^2.*3.0]);
t4 = t0(3);
t0 = roots([sf.^2.*1.2e+3,sf.*v0.*-9.6e+2-sf.*vf.*9.6e+2,a0.*sf.*-1.2e+2+v0.*vf.*3.36e+2+v0.^2.*1.92e+2+vf.^2.*1.92e+2,a0.*v0.*4.8e+1+a0.*vf.*3.2e+1,a0.^2.*3.0]);
t5 = t0(4);
final_opt_time_pass_var = [1.0./t2;1.0./t3;1.0./t4;1.0./t5];
end
