function final_opt_pos_j0_var = final_opt_pos_j0(v0,a0,T)
%FINAL_OPT_POS_J0
%    FINAL_OPT_POS_J0_VAR = FINAL_OPT_POS_J0(V0,A0,T)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Nov-2025 12:19:33

final_opt_pos_j0_var = T.*(v0.*4.0+T.*a0).*(3.0./2.0e+1);
end
