function accveltest = importdata_vel_acc(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ACCVELTEST = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  ACCVELTEST = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  accveltest = importfile("/Users/alessandrobianchiceriani/Desktop/Scrivania_MPB/ALE_VARIE_DONTTOUCH/UNITN/MAGISTRALE/Secondo_Anno/IVAD/Repos/basic_agent_ST/log_internal/acc_vel_test.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Nov-2025 12:02:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", ";"];

% Specify column names and types
opts.VariableNames = ["time", "acc", "req_acc", "vel", "req_vel"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
accveltest = readtable(filename, opts);

end