function min_vel_var = min_vel(v0,a0,sf)
%MIN_VEL
%    MIN_VEL_VAR = MIN_VEL(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Oct-2025 11:35:05

t2 = a0.*sf;
t3 = -t2;
min_vel_var = 1.0./sqrt(t3).*(sqrt(1.5e+1).*t2.*2.0+sqrt(t3).*v0.*7.0).*(-1.0./8.0);
end
