function time_min_vel_var = time_min_vel(a0,sf)
%TIME_MIN_VEL
%    TIME_MIN_VEL_VAR = TIME_MIN_VEL(A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Oct-2025 11:35:05

t2 = a0.*sf;
t3 = 1.0./a0;
t5 = sqrt(1.5e+1);
t4 = -t2;
t6 = sqrt(t4);
t7 = t3.*t5.*t6;
time_min_vel_var = [t7;-t7];
end
