/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * primitives.c
 *
 * Code generation for function 'primitives'
 *
 */

/* Include files */
#include "primitives.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Variable Definitions */
static boolean_T isInitialized_primitives = false;

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
static double rt_powd_snf(double u0, double u1)
{
  double d;
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    y = fabs(u0);
    d = fabs(u1);
    if (rtIsInf(u1)) {
      if (y == 1.0) {
        y = 1.0;
      } else if (y > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d == 0.0) {
      y = 1.0;
    } else if (d == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * function out1 = a_opt(t,v0,a0,sf,vf,af,T)
 */
double a_opt(double t, double v0, double a0, double sf, double vf, double af,
             double T)
{
  double b_out1_tmp;
  double out1;
  double out1_tmp;
  double t3;
  double t4;
  double t4_tmp;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /* A_OPT */
  /*     OUT1 = A_OPT(t,V0,A0,SF,VF,AF,T) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     15-Dec-2025 18:17:31 */
  /* 'a_opt:8' t2 = T.^2; */
  out1 = T * T;
  /* 'a_opt:9' t3 = af.*t2; */
  t3 = af * out1;
  /* 'a_opt:10' t4 = a0.*t2.*3.0; */
  t4_tmp = a0 * out1;
  t4 = t4_tmp * 3.0;
  /* 'a_opt:11' t5 = -t3; */
  /* 'a_opt:12' out1 =
   * a0-1.0./T.^5.*t.^3.*(sf.*-1.2e+1+t5+T.*v0.*6.0+T.*vf.*6.0+a0.*t2).*1.0e+1+t.^2.*1.0./t2.^2.*(sf.*-3.0e+1-t3.*2.0+t4+T.*v0.*1.6e+1+T.*vf.*1.4e+1).*6.0-1.0./T.^3.*t.*(sf.*-2.0e+1+t4+t5+T.*v0.*1.2e+1+T.*vf.*8.0).*3.0;
   */
  out1_tmp = T * v0;
  b_out1_tmp = T * vf;
  return ((a0 - 1.0 / rt_powd_snf(T, 5.0) * rt_powd_snf(t, 3.0) *
                    ((((sf * -12.0 - t3) + out1_tmp * 6.0) + b_out1_tmp * 6.0) +
                     t4_tmp) *
                    10.0) +
          t * t / (out1 * out1) *
              ((((sf * -30.0 - t3 * 2.0) + t4) + out1_tmp * 16.0) +
               b_out1_tmp * 14.0) *
              6.0) -
         1.0 / rt_powd_snf(T, 3.0) * t *
             ((((sf * -20.0 + t4) - t3) + out1_tmp * 12.0) + b_out1_tmp * 8.0) *
             3.0;
}

/*
 * function coef_list_var = coef_list_fun(v0,a0,sf,vf,af,T)
 */
void coef_list_fun(double v0, double a0, double sf, double vf, double af,
                   double T, double coef_list_var[6])
{
  double b_coef_list_var_tmp;
  double coef_list_var_tmp;
  double t2;
  double t3;
  double t4;
  double t4_tmp;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /* COEF_LIST_FUN */
  /*     COEF_LIST_VAR = COEF_LIST_FUN(V0,A0,SF,VF,AF,T) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     15-Dec-2025 18:17:31 */
  /* 'coef_list_fun:8' t2 = T.^2; */
  t2 = T * T;
  /* 'coef_list_fun:9' t3 = af.*t2; */
  t3 = af * t2;
  /* 'coef_list_fun:10' t4 = a0.*t2.*3.0; */
  t4_tmp = a0 * t2;
  t4 = t4_tmp * 3.0;
  /* 'coef_list_fun:11' t5 = -t3; */
  /* 'coef_list_fun:12' coef_list_var =
   * [0.0,v0,a0,1.0./T.^3.*(sf.*-2.0e+1+t4+t5+T.*v0.*1.2e+1+T.*vf.*8.0).*-3.0,1.0./t2.^2.*(sf.*-3.0e+1-t3.*2.0+t4+T.*v0.*1.6e+1+T.*vf.*1.4e+1).*1.2e+1,1.0./T.^5.*(sf.*-1.2e+1+t5+T.*v0.*6.0+T.*vf.*6.0+a0.*t2).*-6.0e+1];
   */
  coef_list_var[0] = 0.0;
  coef_list_var[1] = v0;
  coef_list_var[2] = a0;
  coef_list_var_tmp = T * v0;
  b_coef_list_var_tmp = T * vf;
  coef_list_var[3] = 1.0 / rt_powd_snf(T, 3.0) *
                     ((((sf * -20.0 + t4) - t3) + coef_list_var_tmp * 12.0) +
                      b_coef_list_var_tmp * 8.0) *
                     -3.0;
  coef_list_var[4] =
      1.0 / (t2 * t2) *
      ((((sf * -30.0 - t3 * 2.0) + t4) + coef_list_var_tmp * 16.0) +
       b_coef_list_var_tmp * 14.0) *
      12.0;
  coef_list_var[5] = 1.0 / rt_powd_snf(T, 5.0) *
                     ((((sf * -12.0 - t3) + coef_list_var_tmp * 6.0) +
                       b_coef_list_var_tmp * 6.0) +
                      t4_tmp) *
                     -60.0;
}

void primitives_initialize(void)
{
  rt_InitInfAndNaN();
  isInitialized_primitives = true;
}

void primitives_terminate(void)
{
  isInitialized_primitives = false;
}

/*
 * function out1 = s_opt(t,v0,a0,sf,vf,af,T)
 */
double s_opt(double t, double v0, double a0, double sf, double vf, double af,
             double T)
{
  double b_out1_tmp;
  double out1;
  double out1_tmp;
  double t3;
  double t4;
  double t4_tmp;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /* S_OPT */
  /*     OUT1 = S_OPT(t,V0,A0,SF,VF,AF,T) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     15-Dec-2025 18:17:30 */
  /* 's_opt:8' t2 = T.^2; */
  out1 = T * T;
  /* 's_opt:9' t3 = af.*t2; */
  t3 = af * out1;
  /* 's_opt:10' t4 = a0.*t2.*3.0; */
  t4_tmp = a0 * out1;
  t4 = t4_tmp * 3.0;
  /* 's_opt:11' t5 = -t3; */
  /* 's_opt:12' out1 =
   * t.*v0+(a0.*t.^2)./2.0-(1.0./T.^5.*t.^5.*(sf.*-1.2e+1+t5+T.*v0.*6.0+T.*vf.*6.0+a0.*t2))./2.0-(1.0./T.^3.*t.^3.*(sf.*-2.0e+1+t4+t5+T.*v0.*1.2e+1+T.*vf.*8.0))./2.0+(t.^4.*1.0./t2.^2.*(sf.*-3.0e+1-t3.*2.0+t4+T.*v0.*1.6e+1+T.*vf.*1.4e+1))./2.0;
   */
  out1_tmp = T * v0;
  b_out1_tmp = T * vf;
  return (((t * v0 + a0 * (t * t) / 2.0) -
           1.0 / rt_powd_snf(T, 5.0) * rt_powd_snf(t, 5.0) *
               ((((sf * -12.0 - t3) + out1_tmp * 6.0) + b_out1_tmp * 6.0) +
                t4_tmp) /
               2.0) -
          1.0 / rt_powd_snf(T, 3.0) * rt_powd_snf(t, 3.0) *
              ((((sf * -20.0 + t4) - t3) + out1_tmp * 12.0) +
               b_out1_tmp * 8.0) /
              2.0) +
         rt_powd_snf(t, 4.0) / (out1 * out1) *
             ((((sf * -30.0 - t3 * 2.0) + t4) + out1_tmp * 16.0) +
              b_out1_tmp * 14.0) /
             2.0;
}

/*
 * function [coeffsT2, v2, T2, coeffsT1, v1, T1] = student_pass_primitive(v0,
 * a0, sf, vfmin, vfmax, Tmin, Tmax)
 */
void student_pass_primitive(double v0, double a0, double sf, double vfmin,
                            double vfmax, double Tmin, double Tmax,
                            double coeffsT2_data[], int coeffsT2_size[2],
                            double *v2, double *T2, double coeffsT1_data[],
                            int coeffsT1_size[2], double *v1, double *T1)
{
  double dv[6];
  double Tvmin;
  double t2_tmp;
  double v_star;
  int i;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /*  */
  /*            Agent Logic */
  /*          Pass Primitive */
  /*               2025 */
  /*  */
  /* 'student_pass_primitive:11' if a0 >= 0 */
  if (a0 >= 0.0) {
    /* 'student_pass_primitive:12' Tvmin = final_opt_time_pass(v0, a0, sf,
     * vfmin); */
    /* FINAL_OPT_TIME_PASS */
    /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     15-Dec-2025 18:17:35 */
    /* 'final_opt_time_pass:8' out1 =
     * (sf.*3.0e+1)./(v0.*7.0+vf.*8.0+sqrt(a0.*sf.*6.0e+1+v0.*vf.*1.12e+2+v0.^2.*4.9e+1+vf.^2.*6.4e+1));
     */
    v_star = a0 * sf * 60.0;
    t2_tmp = v0 * v0 * 49.0;
    Tvmin =
        sf * 30.0 /
        ((v0 * 7.0 + vfmin * 8.0) +
         sqrt(((v_star + v0 * vfmin * 112.0) + t2_tmp) + vfmin * vfmin * 64.0));
    /* 'student_pass_primitive:13' Tvmax = final_opt_time_pass(v0, a0, sf,
     * vfmax); */
    /* FINAL_OPT_TIME_PASS */
    /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     15-Dec-2025 18:17:35 */
    /* 'final_opt_time_pass:8' out1 =
     * (sf.*3.0e+1)./(v0.*7.0+vf.*8.0+sqrt(a0.*sf.*6.0e+1+v0.*vf.*1.12e+2+v0.^2.*4.9e+1+vf.^2.*6.4e+1));
     */
    v_star =
        sf * 30.0 /
        ((v0 * 7.0 + vfmax * 8.0) +
         sqrt(((v_star + v0 * vfmax * 112.0) + t2_tmp) + vfmax * vfmax * 64.0));
  } else {
    /* 'student_pass_primitive:14' else */
    /* 'student_pass_primitive:15' T_star = time_min_vel(a0, sf); */
    /* TIME_MIN_VEL */
    /*     OUT1 = TIME_MIN_VEL(A0,SF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     15-Dec-2025 18:17:35 */
    /* 'time_min_vel:8' out1 = (sqrt(1.5e+1).*sqrt(-a0.*sf))./a0; */
    /* 'student_pass_primitive:16' v_star = min_vel(v0, a0, sf); */
    /* MIN_VEL */
    /*     MIN_VEL_VAR = MIN_VEL(V0,A0,SF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     15-Dec-2025 18:17:35 */
    /* 'min_vel:8' t2 = a0.*sf; */
    t2_tmp = a0 * sf;
    /* 'min_vel:9' t3 = -t2; */
    /* 'min_vel:10' min_vel_var
     * = 1.0./sqrt(t3).*(sqrt(1.5e+1).*t2.*2.0+sqrt(t3).*v0.*7.0).*(-1.0./8.0);
     */
    v_star = sqrt(-t2_tmp);
    v_star = 1.0 / v_star *
             (3.872983346207417 * t2_tmp * 2.0 + v_star * v0 * 7.0) * -0.125;
    /* 'student_pass_primitive:17' if v_star < vfmin && vfmin < vfmax */
    if ((v_star < vfmin) && (vfmin < vfmax)) {
      /* 'student_pass_primitive:18' Tvmin = final_opt_time_pass(v0, a0, sf,
       * vfmin); */
      /* FINAL_OPT_TIME_PASS */
      /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.2. */
      /*     15-Dec-2025 18:17:35 */
      /* 'final_opt_time_pass:8' out1 =
       * (sf.*3.0e+1)./(v0.*7.0+vf.*8.0+sqrt(a0.*sf.*6.0e+1+v0.*vf.*1.12e+2+v0.^2.*4.9e+1+vf.^2.*6.4e+1));
       */
      v_star = t2_tmp * 60.0;
      t2_tmp = v0 * v0 * 49.0;
      Tvmin = sf * 30.0 /
              ((v0 * 7.0 + vfmin * 8.0) +
               sqrt(((v_star + v0 * vfmin * 112.0) + t2_tmp) +
                    vfmin * vfmin * 64.0));
      /* 'student_pass_primitive:19' Tvmax = final_opt_time_pass(v0, a0, sf,
       * vfmax); */
      /* FINAL_OPT_TIME_PASS */
      /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.2. */
      /*     15-Dec-2025 18:17:35 */
      /* 'final_opt_time_pass:8' out1 =
       * (sf.*3.0e+1)./(v0.*7.0+vf.*8.0+sqrt(a0.*sf.*6.0e+1+v0.*vf.*1.12e+2+v0.^2.*4.9e+1+vf.^2.*6.4e+1));
       */
      v_star = sf * 30.0 /
               ((v0 * 7.0 + vfmax * 8.0) +
                sqrt(((v_star + v0 * vfmax * 112.0) + t2_tmp) +
                     vfmax * vfmax * 64.0));
    } else if ((vfmin < v_star) && (v_star < vfmax)) {
      /* 'student_pass_primitive:20' elseif vfmin < v_star && v_star < vfmax */
      /* 'student_pass_primitive:21' Tvmin = T_star; */
      Tvmin = 3.872983346207417 * sqrt(-a0 * sf) / a0;
      /* 'student_pass_primitive:22' Tvmax = final_opt_time_pass(v0, a0, sf,
       * vfmax); */
      /* FINAL_OPT_TIME_PASS */
      /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.2. */
      /*     15-Dec-2025 18:17:35 */
      /* 'final_opt_time_pass:8' out1 =
       * (sf.*3.0e+1)./(v0.*7.0+vf.*8.0+sqrt(a0.*sf.*6.0e+1+v0.*vf.*1.12e+2+v0.^2.*4.9e+1+vf.^2.*6.4e+1));
       */
      v_star = sf * 30.0 /
               ((v0 * 7.0 + vfmax * 8.0) +
                sqrt(((t2_tmp * 60.0 + v0 * vfmax * 112.0) + v0 * v0 * 49.0) +
                     vfmax * vfmax * 64.0));
    } else {
      /* 'student_pass_primitive:23' else */
      /* 'student_pass_primitive:24' Tvmin = 0.; */
      Tvmin = 0.0;
      /* 'student_pass_primitive:25' Tvmax = 0.; */
      v_star = 0.0;
    }
  }
  /*  FREE-FLOW PRIMITIVE */
  /* 'student_pass_primitive:30' if Tmin == 0. && Tmax == 0. */
  if ((Tmin == 0.0) && (Tmax == 0.0)) {
    /* 'student_pass_primitive:31' T1 = Tvmin; */
    *T1 = Tvmin;
    /* 'student_pass_primitive:32' T2 = Tvmax; */
    *T2 = v_star;
    /*  FREE-FLOW PRIMITIVE */
  } else {
    /* 'student_pass_primitive:34' else */
    /* 'student_pass_primitive:35' T1 = max(Tmin, Tvmax); */
    if ((Tmin >= v_star) || rtIsNaN(v_star)) {
      *T1 = Tmin;
    } else {
      *T1 = v_star;
    }
    /* 'student_pass_primitive:36' T2 = min(Tmax, Tvmin); */
    if ((Tmax <= Tvmin) || rtIsNaN(Tvmin)) {
      *T2 = Tmax;
    } else {
      *T2 = Tvmin;
    }
  }
  /* 'student_pass_primitive:39' if Tvmax ~= 0 && Tvmax <= Tvmin && T1 > 0 && T1
   * <= T2 */
  if ((v_star != 0.0) && (v_star <= Tvmin) && (*T1 > 0.0) && (*T1 <= *T2)) {
    /* 'student_pass_primitive:40' v1 = final_opt_vel_pass(v0, a0, sf, T1); */
    /* FINAL_OPT_VEL_PASS */
    /*     FINAL_OPT_VEL_PASS_VAR = FINAL_OPT_VEL_PASS(V0,A0,SF,T) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     15-Dec-2025 18:17:35 */
    /* 'final_opt_vel_pass:8' final_opt_vel_pass_var =
     * ((sf.*-1.5e+1+T.*v0.*7.0+T.^2.*a0).*(-1.0./8.0))./T; */
    *v1 = ((sf * -15.0 + *T1 * v0 * 7.0) + *T1 * *T1 * a0) * -0.125 / *T1;
    /* 'student_pass_primitive:41' v2 = final_opt_vel_pass(v0, a0, sf, T2); */
    /* FINAL_OPT_VEL_PASS */
    /*     FINAL_OPT_VEL_PASS_VAR = FINAL_OPT_VEL_PASS(V0,A0,SF,T) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     15-Dec-2025 18:17:35 */
    /* 'final_opt_vel_pass:8' final_opt_vel_pass_var =
     * ((sf.*-1.5e+1+T.*v0.*7.0+T.^2.*a0).*(-1.0./8.0))./T; */
    *v2 = ((sf * -15.0 + *T2 * v0 * 7.0) + *T2 * *T2 * a0) * -0.125 / *T2;
    /* 'student_pass_primitive:42' coeffsT1 = coef_list_fun(v0, a0, sf, v1, 0.,
     * T1); */
    coef_list_fun(v0, a0, sf, *v1, 0.0, *T1, dv);
    coeffsT1_size[0] = 1;
    coeffsT1_size[1] = 6;
    for (i = 0; i < 6; i++) {
      coeffsT1_data[i] = dv[i];
    }
    /* 'student_pass_primitive:43' coeffsT2 = coef_list_fun(v0, a0, sf, v2, 0.,
     * T2); */
    coef_list_fun(v0, a0, sf, *v2, 0.0, *T2, dv);
    coeffsT2_size[0] = 1;
    coeffsT2_size[1] = 6;
    for (i = 0; i < 6; i++) {
      coeffsT2_data[i] = dv[i];
    }
  } else {
    /* 'student_pass_primitive:44' else */
    /* 'student_pass_primitive:45' coeffsT1 = [0.;0.;0.;0.;0.;0.]; */
    coeffsT1_size[0] = 6;
    coeffsT1_size[1] = 1;
    /* 'student_pass_primitive:46' coeffsT2 = [0.;0.;0.;0.;0.;0.]; */
    coeffsT2_size[0] = 6;
    coeffsT2_size[1] = 1;
    for (i = 0; i < 6; i++) {
      coeffsT1_data[i] = 0.0;
      coeffsT2_data[i] = 0.0;
    }
    /* 'student_pass_primitive:47' T1 = 0.; */
    *T1 = 0.0;
    /* 'student_pass_primitive:48' T2 = 0.; */
    *T2 = 0.0;
    /* 'student_pass_primitive:49' v1 = 0.; */
    *v1 = 0.0;
    /* 'student_pass_primitive:50' v2 = 0.; */
    *v2 = 0.0;
  }
}

/*
 * function [coefsj0, vfj0, tfj0] = pass_primitive_j0(v0, a0, sf, vfmin, vfmax)
 */
void student_pass_primitive_j0(double v0, double a0, double sf, double vfmin,
                               double vfmax, double coefsj0[6], double *vfj0,
                               double *tfj0)
{
  double t2;
  double t9;
  double tfj0_list_idx_0;
  int i;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /*  */
  /*           Agent Logic */
  /*          Pass Primitive J0 */
  /*               2025 */
  /*  */
  /* 'student_pass_primitive_j0:11' tfj0_list = final_opt_time_pass_j0(v0, a0,
   * sf); */
  /* FINAL_OPT_TIME_PASS_J0 */
  /*     FINAL_OPT_TIME_PASS_J0_VAR = FINAL_OPT_TIME_PASS_J0(V0,A0,SF) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     15-Dec-2025 18:18:06 */
  /* 'final_opt_time_pass_j0:8' t2 = v0.*5.0; */
  t2 = v0 * 5.0;
  /* 'final_opt_time_pass_j0:9' t4 = a0.*sf.*8.0; */
  /* 'final_opt_time_pass_j0:10' t6 = sqrt(5.0); */
  /* 'final_opt_time_pass_j0:11' t5 = t2.*v0; */
  /* 'final_opt_time_pass_j0:12' t7 = t4+t5; */
  /* 'final_opt_time_pass_j0:13' t8 = sqrt(t7); */
  /* 'final_opt_time_pass_j0:14' t9 = t6.*t8; */
  t9 = 2.23606797749979 * sqrt(a0 * sf * 8.0 + t2 * v0);
  /* 'final_opt_time_pass_j0:15' final_opt_time_pass_j0_var =
   * [(sf.*1.0e+1)./(t2+t9);(sf.*1.0e+1)./(t2-t9)]; */
  tfj0_list_idx_0 = sf * 10.0 / (t2 + t9);
  *tfj0 = sf * 10.0 / (t2 - t9);
  /* 'student_pass_primitive_j0:12' vfj0 =
   * final_opt_vel_pass_j0(v0,a0,0,sf,0,tfj0_list(1)); */
  /* FINAL_OPT_VEL_PASS_J0 */
  /*     FINAL_OPT_VEL_PASS_J0_VAR = FINAL_OPT_VEL_PASS_J0(V0,A0,J0,SF,AF,T) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     15-Dec-2025 18:18:06 */
  /* 'final_opt_vel_pass_j0:8' t2 = T.^2; */
  t2 = tfj0_list_idx_0 * tfj0_list_idx_0;
  /* 'final_opt_vel_pass_j0:9' final_opt_vel_pass_j0_var =
   * ((sf.*-6.0e+1+T.*v0.*3.6e+1+a0.*t2.*9.0-af.*t2.*3.0+T.^3.*j0).*(-1.0./2.4e+1))./T;
   */
  *vfj0 = ((((sf * -60.0 + tfj0_list_idx_0 * v0 * 36.0) + a0 * t2 * 9.0) -
            0.0 * t2 * 3.0) +
           rt_powd_snf(tfj0_list_idx_0, 3.0) * 0.0) *
          -0.041666666666666664 / tfj0_list_idx_0;
  /* 'student_pass_primitive_j0:13' if vfmin < vfj0 && vfmax > vfj0 */
  if ((vfmin < *vfj0) && (vfmax > *vfj0)) {
    /* 'student_pass_primitive_j0:14' tfj0 = tfj0_list(1); */
    *tfj0 = tfj0_list_idx_0;
    /* 'student_pass_primitive_j0:15' coefsj0 = coef_list_fun(v0, a0, sf, vfj0,
     * 0., tfj0); */
    coef_list_fun(v0, a0, sf, *vfj0, 0.0, tfj0_list_idx_0, coefsj0);
  } else {
    /* 'student_pass_primitive_j0:16' else */
    /* 'student_pass_primitive_j0:17' vfj0 =
     * final_opt_vel_pass_j0(v0,a0,0,sf,0,tfj0_list(2)); */
    /* FINAL_OPT_VEL_PASS_J0 */
    /*     FINAL_OPT_VEL_PASS_J0_VAR = FINAL_OPT_VEL_PASS_J0(V0,A0,J0,SF,AF,T)
     */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     15-Dec-2025 18:18:06 */
    /* 'final_opt_vel_pass_j0:8' t2 = T.^2; */
    t2 = *tfj0 * *tfj0;
    /* 'final_opt_vel_pass_j0:9' final_opt_vel_pass_j0_var =
     * ((sf.*-6.0e+1+T.*v0.*3.6e+1+a0.*t2.*9.0-af.*t2.*3.0+T.^3.*j0).*(-1.0./2.4e+1))./T;
     */
    *vfj0 =
        ((((sf * -60.0 + *tfj0 * v0 * 36.0) + a0 * t2 * 9.0) - 0.0 * t2 * 3.0) +
         rt_powd_snf(*tfj0, 3.0) * 0.0) *
        -0.041666666666666664 / *tfj0;
    /* 'student_pass_primitive_j0:18' if vfmin < vfj0 && vfmax > vfj0 */
    if ((vfmin < *vfj0) && (vfmax > *vfj0)) {
      /* 'student_pass_primitive_j0:19' tfj0 = tfj0_list(2); */
      /* 'student_pass_primitive_j0:20' coefsj0 = coef_list_fun(v0, a0, sf,
       * vfj0, 0., tfj0); */
      coef_list_fun(v0, a0, sf, *vfj0, 0.0, *tfj0, coefsj0);
    } else {
      /* 'student_pass_primitive_j0:21' else */
      /* 'student_pass_primitive_j0:22' coefsj0 = [0.,0.,0.,0.,0.,0.]; */
      for (i = 0; i < 6; i++) {
        coefsj0[i] = 0.0;
      }
      /* 'student_pass_primitive_j0:23' tfj0 = 0.; */
      *tfj0 = 0.0;
      /* 'student_pass_primitive_j0:24' vfj0 = 0.; */
      *vfj0 = 0.0;
    }
  }
}

/*
 * function [coefs,maxsf,tf] = student_stop_primitive(v0,a0,sf)
 */
void student_stop_primitive(double v0, double a0, double sf, double coefs[6],
                            double *maxsf, double *tf)
{
  double d;
  int i;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /*  */
  /*           Agent Logic */
  /*          Stop Primitive */
  /*               2025 */
  /*  */
  /*  Impossible cases: negative velocity and null final position --> */
  /*  return 0 */
  /* 'student_stop_primitive:11' if (v0 <= 0) || (sf == 0) */
  if ((v0 <= 0.0) || (sf == 0.0)) {
    /* 'student_stop_primitive:12' coefs = [0,0,0,0,0,0]; */
    for (i = 0; i < 6; i++) {
      coefs[i] = 0.0;
    }
    /*  Returns a vector of 6 zeros for each coefficient */
    /* 'student_stop_primitive:13' tf = 0.; */
    *tf = 0.0;
    /* 'student_stop_primitive:14' maxsf = 0.; */
    *maxsf = 0.0;
    /*  Also set other returns to 0 */
  } else {
    /* 'student_stop_primitive:15' else */
    /*  Can't reach a specified sf using given inputs (v0, a0) */
    /* 'student_stop_primitive:17' if 4*v0^2 + 5*a0*sf < 0 */
    d = 4.0 * (v0 * v0);
    if (d + 5.0 * a0 * sf < 0.0) {
      /* 'student_stop_primitive:18' maxsf = - (4*v0^2)/(5*a0); */
      *maxsf = -d / (5.0 * a0);
      /* 'student_stop_primitive:19' tf = (5*maxsf)/v0; */
      *tf = 5.0 * *maxsf / v0;
    } else {
      /* 'student_stop_primitive:20' else */
      /*  Valid case: compute final time with defined function */
      /* 'student_stop_primitive:22' maxsf = sf; */
      *maxsf = sf;
      /* 'student_stop_primitive:23' tf = final_opt_time_stop(v0, a0, maxsf); */
      /* FINAL_OPT_TIME_STOP */
      /*     OUT1 = FINAL_OPT_TIME_STOP(V0,A0,SF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.2. */
      /*     15-Dec-2025 18:03:45 */
      /* 'final_opt_time_stop:8' out1 =
       * (sf.*1.0e+1)./(v0.*2.0+sqrt(a0.*sf.*5.0+v0.^2.*4.0)); */
      *tf = sf * 10.0 / (v0 * 2.0 + sqrt(a0 * sf * 5.0 + d));
    }
    /*  Evaluate coefficients (consider vf = af = 0) */
    /* 'student_stop_primitive:27' coefs = coef_list_fun(v0, a0, 0., 0., 0.,
     * tf); */
    coef_list_fun(v0, a0, 0.0, 0.0, 0.0, *tf, coefs);
  }
}

/*
 * function [coefsj0,sfj0,tfj0] = student_stop_primitive_j0(v0,a0)
 */
void student_stop_primitive_j0(double v0, double a0, double coefsj0[6],
                               double *sfj0, double *tfj0)
{
  int i;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /*  */
  /*            Agent Logic */
  /*          Stop Primitive J0 */
  /*               2025 */
  /*  */
  /* 'student_stop_primitive_j0:11' if v0 > 0 && a0 < 0 */
  if ((v0 > 0.0) && (a0 < 0.0)) {
    /* 'student_stop_primitive_j0:12' tfj0 = final_opt_time_stop_j0(v0, a0); */
    /* FINAL_OPT_TIME_STOP_J0 */
    /*     OUT1 = FINAL_OPT_TIME_STOP_J0(V0,A0) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     21-Nov-2025 12:22:45 */
    /* 'final_opt_time_stop_j0:8' out1 = (v0.*-2.0)./a0; */
    *tfj0 = v0 * -2.0 / a0;
    /* 'student_stop_primitive_j0:13' sfj0 = final_opt_pos_j0(v0, a0, tfj0); */
    /* FINAL_OPT_POS_J0 */
    /*     FINAL_OPT_POS_J0_VAR = FINAL_OPT_POS_J0(V0,A0,T) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.2. */
    /*     21-Nov-2025 12:19:33 */
    /* 'final_opt_pos_j0:8' final_opt_pos_j0_var =
     * T.*(v0.*4.0+T.*a0).*(3.0./2.0e+1); */
    *sfj0 = *tfj0 * (v0 * 4.0 + *tfj0 * a0) * 0.15;
    /* 'student_stop_primitive_j0:14' coefsj0 = coef_list_fun(v0, a0, sfj0, 0.,
     * 0., tfj0); */
    coef_list_fun(v0, a0, *sfj0, 0.0, 0.0, *tfj0, coefsj0);
  } else {
    /* 'student_stop_primitive_j0:15' else */
    /* 'student_stop_primitive_j0:16' tfj0 = 0.; */
    *tfj0 = 0.0;
    /* 'student_stop_primitive_j0:17' sfj0 = 0.; */
    *sfj0 = 0.0;
    /* 'student_stop_primitive_j0:18' coefsj0 = [0., 0., 0., 0., 0., 0.]; */
    for (i = 0; i < 6; i++) {
      coefsj0[i] = 0.0;
    }
  }
}

/*
 * function out1 = v_opt(t,v0,a0,sf,vf,af,T)
 */
double v_opt(double t, double v0, double a0, double sf, double vf, double af,
             double T)
{
  double b_out1_tmp;
  double out1;
  double out1_tmp;
  double t3;
  double t4;
  double t4_tmp;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /* V_OPT */
  /*     OUT1 = V_OPT(t,V0,A0,SF,VF,AF,T) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     15-Dec-2025 18:17:31 */
  /* 'v_opt:8' t2 = T.^2; */
  out1 = T * T;
  /* 'v_opt:9' t3 = af.*t2; */
  t3 = af * out1;
  /* 'v_opt:10' t4 = a0.*t2.*3.0; */
  t4_tmp = a0 * out1;
  t4 = t4_tmp * 3.0;
  /* 'v_opt:11' t5 = -t3; */
  /* 'v_opt:12' out1 =
   * v0+a0.*t-1.0./T.^5.*t.^4.*(sf.*-1.2e+1+t5+T.*v0.*6.0+T.*vf.*6.0+a0.*t2).*(5.0./2.0)-1.0./T.^3.*t.^2.*(sf.*-2.0e+1+t4+t5+T.*v0.*1.2e+1+T.*vf.*8.0).*(3.0./2.0)+t.^3.*1.0./t2.^2.*(sf.*-3.0e+1-t3.*2.0+t4+T.*v0.*1.6e+1+T.*vf.*1.4e+1).*2.0;
   */
  out1_tmp = T * v0;
  b_out1_tmp = T * vf;
  return (((v0 + a0 * t) -
           1.0 / rt_powd_snf(T, 5.0) * rt_powd_snf(t, 4.0) *
               ((((sf * -12.0 - t3) + out1_tmp * 6.0) + b_out1_tmp * 6.0) +
                t4_tmp) *
               2.5) -
          1.0 / rt_powd_snf(T, 3.0) * (t * t) *
              ((((sf * -20.0 + t4) - t3) + out1_tmp * 12.0) +
               b_out1_tmp * 8.0) *
              1.5) +
         rt_powd_snf(t, 3.0) / (out1 * out1) *
             ((((sf * -30.0 - t3 * 2.0) + t4) + out1_tmp * 16.0) +
              b_out1_tmp * 14.0) *
             2.0;
}

/* End of code generation (primitives.c) */
